/// Flutter icons ProfileLinkIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ProfileLinkIcons
///      fonts:
///       - asset: fonts/ProfileLinkIcons.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class ProfileLinkIcons {
  ProfileLinkIcons._();

  static const _kFontFam = 'ProfileLinkIcons';
  static const String? _kFontPkg = null;

  static const IconData linkedin = IconData(0xf08c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = IconData(0xf09b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stackoverflow = IconData(0xf16c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData codepen = IconData(0xf1cb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
